services:
  frontend:
    image: ghcr.io/nookpost/nookpost-frontend:v0.27.0
    environment:
      - BACKEND_URL=http://localhost:8080
    networks:
      - nookpost
  backend:
    image: ghcr.io/nookpost/nookpost-backend:v0.13.6
    networks:
      - nookpost
  proxy:
    ports:
      - 8080:80
    image: nginx:1.27.4
    volumes:
      - "./nginx.conf:/etc/nginx/conf.d/default.conf:ro"
    networks:
      - nookpost
networks:
  nookpost:
